### ISSUE TITLE
lobby bug: extra player

### ISSUE THREAD

**Issue by sebosh** [Dumba/t-rex#13]
# a bug where one player shows up in lobby for others even when he has left

## initial setup

open the game in one browser tab and host a lobby

## reproduction

1. click the [here]() link to get a new browser tab with the lobby for another user (this time the user has joined via url so this tabs url contains the gameId)
2. go to the first tab (where the lobby was initially hosted) and leave the lobby
3. the first user disappears from the players list in the second tab but after refresh (refresh works because of the url) he shows up again

## desired output

the first user should not show up again in the players list after he leaves the lobby

## actual output i got

the first user shows up in the players list again after refresh

## notes

this bug works even with more players but only one extra user appears (when repeated with another one, doesnt reappear) and it is the one that hosted the lobby first

**Comment by Dumba** [comment]
Fixed.

Player was attached to game but game was not attached to player (game creator).

Now you will be kicked out, when you are last player in game and you refresh page. Game is destroyed after all players left.
